sudo: false
osx_image: xcode10
language: objective-c
rvm:
  - 2.6.0
xcode_project: PureLayout/PureLayout.xcodeproj
before_install:
  - rvm install 2.6.0
  - gem install slather --no-document

script:
  - xcodebuild test -project PureLayout/PureLayout.xcodeproj -scheme PureLayout_iOS -destination 'platform=iOS Simulator,name=iPhone X,OS=11.2'
  - xcodebuild test -project PureLayout/PureLayout.xcodeproj -scheme PureLayout_iOS -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
  - xcodebuild test -project PureLayout/PureLayout.xcodeproj -scheme PureLayout_iOS -destination 'platform=iOS Simulator,name=iPhone 5s,OS=9.0'
  - xcodebuild test -project PureLayout/PureLayout.xcodeproj -scheme PureLayout_Mac -destination 'platform=OS X,arch=x86_64'

after_success: slather
